### PR TITLE
Analysis 0.6 Monitor DB replication delay

### PR DESCRIPTION
**Pull request by FedericoCeratto**

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
deployed

**Comment by FedericoCeratto** [comment]
```
grep delay /run/nodeexp/db_metrics.prom
measurements_flow{type="replication_delay"} 5.469865
```

**Comment by FedericoCeratto** [comment]
Grafana alert added: "AMSDB replication delay is above 60 seconds"

**Review by hellais — APPROVED** [review]
LGTM

**Pull request merged**
