### PR TITLE
Add domain_input and citizenlab tables and update tool

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Implements https://github.com/ooni/api/issues/135 https://github.com/ooni/pipeline/issues/263 https://github.com/ooni/pipeline/issues/258

### CODE REVIEW

**Review by hellais — APPROVED** [review]
We discussed this and this looks good to me.

We should not forget, though, to add also the indexes which we created manually on the DB.

Merge this when you think it's most appropriate.

**Review by hellais — CHANGES_REQUESTED** [review]
For the SQL migration script, the rollback file is missing.

**Review by hellais — APPROVED** [review]
🐳

**Comment by FedericoCeratto** [comment]
Deployed 0.8~pr271-77

**Pull request merged**
